version: '3.8'

services:

    db:
        container_name: db
        image: postgres:13.0-alpine
        volumes:
            - db:/var/lib/postgresql/data/
        env_file:
            - ./.env
        networks:
            - djangonetwork
    web:
        image: sayonararf/api_yamdb:latest
        restart: always
        volumes:
            - static_value:/app/static/
            - media_value:/app/media/
        depends_on:
            - db
        env_file:
            - ./.env
        links:
            - db:db
        networks:
            - djangonetwork
    nginx:
        image: nginx:1.21.3-alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - static_value:/var/html/static/
            - media_value:/var/html/media/
        depends_on:
            - web

networks:
      djangonetwork:
          driver: bridge
volumes:
    db:
    static_value:
    media_value:
